package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int type;
     private String address;
     private String address2;
     private String postal;
     private String city;
     private String state;
     private String country;
     private String firstname;
     private String lastname;
     private String email;
     private String phone;
     private String phone2;
     private String fax;
     private String notes;
     private Boolean visible;
     private BigDecimal maxdebt;
     private BigDecimal curdebt;
     private byte[] image;

    public Accounts() {
    }

	
    public Accounts(String name, int type) {
        this.name = name;
        this.type = type;
    }
    public Accounts(String name, int type, String address, String address2, String postal, String city, String state, String country, String firstname, String lastname, String email, String phone, String phone2, String fax, String notes, Boolean visible, BigDecimal maxdebt, BigDecimal curdebt, byte[] image) {
       this.name = name;
       this.type = type;
       this.address = address;
       this.address2 = address2;
       this.postal = postal;
       this.city = city;
       this.state = state;
       this.country = country;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.phone = phone;
       this.phone2 = phone2;
       this.fax = fax;
       this.notes = notes;
       this.visible = visible;
       this.maxdebt = maxdebt;
       this.curdebt = curdebt;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getPostal() {
        return this.postal;
    }
    
    public void setPostal(String postal) {
        this.postal = postal;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    public BigDecimal getMaxdebt() {
        return this.maxdebt;
    }
    
    public void setMaxdebt(BigDecimal maxdebt) {
        this.maxdebt = maxdebt;
    }
    public BigDecimal getCurdebt() {
        return this.curdebt;
    }
    
    public void setCurdebt(BigDecimal curdebt) {
        this.curdebt = curdebt;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


