package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Alarms generated by hbm2java
 */
public class Alarms  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Boolean active;
     private Integer createdat;
     private Integer updatedat;
     private Integer createdby;

    public Alarms() {
    }

	
    public Alarms(String name) {
        this.name = name;
    }
    public Alarms(String name, String description, Boolean active, Integer createdat, Integer updatedat, Integer createdby) {
       this.name = name;
       this.description = description;
       this.active = active;
       this.createdat = createdat;
       this.updatedat = updatedat;
       this.createdby = createdby;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Integer getCreatedat() {
        return this.createdat;
    }
    
    public void setCreatedat(Integer createdat) {
        this.createdat = createdat;
    }
    public Integer getUpdatedat() {
        return this.updatedat;
    }
    
    public void setUpdatedat(Integer updatedat) {
        this.updatedat = updatedat;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }




}


