package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Purorderdt generated by hbm2java
 */
public class Purorderdt  implements java.io.Serializable {


     private Integer id;
     private int purorderid;
     private int itemid;
     private int qty;
     private BigDecimal price;

    public Purorderdt() {
    }

    public Purorderdt(int purorderid, int itemid, int qty, BigDecimal price) {
       this.purorderid = purorderid;
       this.itemid = itemid;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPurorderid() {
        return this.purorderid;
    }
    
    public void setPurorderid(int purorderid) {
        this.purorderid = purorderid;
    }
    public int getItemid() {
        return this.itemid;
    }
    
    public void setItemid(int itemid) {
        this.itemid = itemid;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


