package com.tss.ocean.pojo;
// Generated 15 Sep, 2014 4:18:30 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PurordApprovers generated by hbm2java
 */
public class PurordApprovers  implements java.io.Serializable {


     private Integer id;
     private int userid;
     private int level;
     private int createdby;
     private Date createdat;

    public PurordApprovers() {
    }

    public PurordApprovers(int userid, int level, int createdby, Date createdat) {
       this.userid = userid;
       this.level = level;
       this.createdby = createdby;
       this.createdat = createdat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }
    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }
    public Date getCreatedat() {
        return this.createdat;
    }
    
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }




}


