package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Purrequisitiondt generated by hbm2java
 */
public class Purrequisitiondt  implements java.io.Serializable {


     private Integer id;
     private int purreqid;
     private int itemid;
     private int qty;
     private BigDecimal price;

    public Purrequisitiondt() {
    }

	
    public Purrequisitiondt(int purreqid, int itemid, int qty) {
        this.purreqid = purreqid;
        this.itemid = itemid;
        this.qty = qty;
    }
    public Purrequisitiondt(int purreqid, int itemid, int qty, BigDecimal price) {
       this.purreqid = purreqid;
       this.itemid = itemid;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPurreqid() {
        return this.purreqid;
    }
    
    public void setPurreqid(int purreqid) {
        this.purreqid = purreqid;
    }
    public int getItemid() {
        return this.itemid;
    }
    
    public void setItemid(int itemid) {
        this.itemid = itemid;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


