package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usertype generated by hbm2java
 */
public class Usertype  implements java.io.Serializable {


     private Integer id;
     private String usertype;
     private String description;
     private Date createdat;
     private Date updateat;

    public Usertype() {
    }

	
    public Usertype(String usertype, Date createdat) {
        this.usertype = usertype;
        this.createdat = createdat;
    }
    public Usertype(String usertype, String description, Date createdat, Date updateat) {
       this.usertype = usertype;
       this.description = description;
       this.createdat = createdat;
       this.updateat = updateat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedat() {
        return this.createdat;
    }
    
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }
    public Date getUpdateat() {
        return this.updateat;
    }
    
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }




}


