package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private Integer usertypeid;
     private Boolean isactive;
     private Date createdat;
     private Date updateat;
     private byte[] image;

    public Users() {
    }

	
    public Users(String name, Date createdat) {
        this.name = name;
        this.createdat = createdat;
    }
    public Users(String name, String password, Integer usertypeid, Boolean isactive, Date createdat, Date updateat, byte[] image) {
       this.name = name;
       this.password = password;
       this.usertypeid = usertypeid;
       this.isactive = isactive;
       this.createdat = createdat;
       this.updateat = updateat;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getUsertypeid() {
        return this.usertypeid;
    }
    
    public void setUsertypeid(Integer usertypeid) {
        this.usertypeid = usertypeid;
    }
    public Boolean getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(Boolean isactive) {
        this.isactive = isactive;
    }
    public Date getCreatedat() {
        return this.createdat;
    }
    
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }
    public Date getUpdateat() {
        return this.updateat;
    }
    
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }




}


