package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Alarmevent generated by hbm2java
 */
public class Alarmevent  implements java.io.Serializable {


     private Integer id;
     private int alarmid;
     private Integer value;
     private String description;
     private byte[] attributes;
     private Date expirydate;

    public Alarmevent() {
    }

	
    public Alarmevent(int alarmid) {
        this.alarmid = alarmid;
    }
    public Alarmevent(int alarmid, Integer value, String description, byte[] attributes, Date expirydate) {
       this.alarmid = alarmid;
       this.value = value;
       this.description = description;
       this.attributes = attributes;
       this.expirydate = expirydate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAlarmid() {
        return this.alarmid;
    }
    
    public void setAlarmid(int alarmid) {
        this.alarmid = alarmid;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte[] getAttributes() {
        return this.attributes;
    }
    
    public void setAttributes(byte[] attributes) {
        this.attributes = attributes;
    }
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }




}


