package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA

import org.hibernate.validator.constraints.NotEmpty;




/**
 * EmployeeLeaveTypes generated by hbm2java
 */
public class EmployeeLeaveTypes  implements java.io.Serializable {


     private Integer id;
     @NotEmpty
     private String name;
     @NotEmpty
     private String code;
     private Boolean status;
     private String maxLeaveCount;
     private boolean carryForward;

    public EmployeeLeaveTypes() {
    }

	
    public EmployeeLeaveTypes(boolean carryForward) {
        this.carryForward = carryForward;
    }
    public EmployeeLeaveTypes(String name, String code, Boolean status, String maxLeaveCount, boolean carryForward) {
       this.name = name;
       this.code = code;
       this.status = status;
       this.maxLeaveCount = maxLeaveCount;
       this.carryForward = carryForward;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getMaxLeaveCount() {
        return this.maxLeaveCount;
    }
    
    public void setMaxLeaveCount(String maxLeaveCount) {
        this.maxLeaveCount = maxLeaveCount;
    }
    public boolean isCarryForward() {
        return this.carryForward;
    }
    
    public void setCarryForward(boolean carryForward) {
        this.carryForward = carryForward;
    }




}


