package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Objects;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * Item generated by hbm2java
 *
 * @author Bhavik Ambani
 */
public class Item implements java.io.Serializable {

    private Integer id;
    @NotNull
    private String name;
    private String alias;
    private int categoryid;
    private Itemtype typeid;

    @DecimalMin(value = "0", message = "The decimal value can not be less than 0 digit ")
    private BigDecimal price;
    private int taxid;
    @Min(value = 0, message = "The minimum stock should be 0")
    private int currstock;
    private Itemunit unitid;

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.id);
        hash = 89 * hash + Objects.hashCode(this.name);
        hash = 89 * hash + Objects.hashCode(this.alias);
        hash = 89 * hash + this.categoryid;
        hash = 89 * hash + Objects.hashCode(this.typeid);
        hash = 89 * hash + Objects.hashCode(this.price);
        hash = 89 * hash + this.taxid;
        hash = 89 * hash + this.currstock;
        hash = 89 * hash + Objects.hashCode(this.unitid);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Item other = (Item) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.alias, other.alias)) {
            return false;
        }
        if (this.categoryid != other.categoryid) {
            return false;
        }
        if (!Objects.equals(this.typeid, other.typeid)) {
            return false;
        }
        if (!Objects.equals(this.price, other.price)) {
            return false;
        }
        if (this.taxid != other.taxid) {
            return false;
        }
        if (this.currstock != other.currstock) {
            return false;
        }
        if (!Objects.equals(this.unitid, other.unitid)) {
            return false;
        }
        return true;
    }

    public Item() {
    }

    public Item(String name, String alias, int categoryid, Itemtype typeid, BigDecimal price, int taxid, Itemunit unitid, int currstock) {
        this.name = name;
        this.alias = alias;
        this.categoryid = categoryid;
        this.typeid = typeid;
        this.price = price;
        this.taxid = taxid;
        this.unitid = unitid;
        this.currstock = currstock;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public int getCategoryid() {
        return this.categoryid;
    }

    public void setCategoryid(int categoryid) {
        this.categoryid = categoryid;
    }

    public Itemtype getTypeid() {
        return this.typeid;
    }

    public void setTypeid(Itemtype typeid) {
        this.typeid = typeid;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public int getTaxid() {
        return this.taxid;
    }

    public void setTaxid(int taxid) {
        this.taxid = taxid;
    }

    public Itemunit getUnitid() {
        return this.unitid;
    }

    public void setUnitid(Itemunit unitid) {
        this.unitid = unitid;
    }

    public int getCurrstock() {
        return this.currstock;
    }

    public void setCurrstock(int currstock) {
        this.currstock = currstock;
    }

    @Override
    public String toString() {
        return "Item{" + "id=" + id + ", name=" + name + ", alias=" + alias + ", categoryid=" + categoryid + ", typeid=" + typeid + ", price=" + price + ", taxid=" + taxid + ", currstock=" + currstock + ", unitid=" + unitid + '}';
    }

}
