package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Itemunit generated by hbm2java
 */
public class Itemunit implements java.io.Serializable {

    private Integer id;
    @NotEmpty
    private String name;
    private String description;

    private Set<Item> itemList;

    public Itemunit() {
    }

    public Itemunit(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Item> getItemList() {
        return itemList;
    }

    public void setItemList(Set<Item> itemList) {
        this.itemList = itemList;
    }

    @Override
    public String toString() {
        return "Itemunit";
    }

}
