package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MonthlyPayslips generated by hbm2java
 */
public class MonthlyPayslips  implements java.io.Serializable {


     private Integer id;
     private Date salaryDate;
     private Integer employeeId;
     private Integer payrollCategoryId;
     private String amount;
     private boolean isApproved;
     private Integer approverId;
     private boolean isRejected;
     private Integer rejectorId;
     private String reason;
     private String remark;

    public MonthlyPayslips() {
    }

	
    public MonthlyPayslips(boolean isApproved, boolean isRejected) {
        this.isApproved = isApproved;
        this.isRejected = isRejected;
    }
    public MonthlyPayslips(Date salaryDate, Integer employeeId, Integer payrollCategoryId, String amount, boolean isApproved, Integer approverId, boolean isRejected, Integer rejectorId, String reason, String remark) {
       this.salaryDate = salaryDate;
       this.employeeId = employeeId;
       this.payrollCategoryId = payrollCategoryId;
       this.amount = amount;
       this.isApproved = isApproved;
       this.approverId = approverId;
       this.isRejected = isRejected;
       this.rejectorId = rejectorId;
       this.reason = reason;
       this.remark = remark;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getSalaryDate() {
        return this.salaryDate;
    }
    
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Integer getPayrollCategoryId() {
        return this.payrollCategoryId;
    }
    
    public void setPayrollCategoryId(Integer payrollCategoryId) {
        this.payrollCategoryId = payrollCategoryId;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public boolean isIsApproved() {
        return this.isApproved;
    }
    
    public void setIsApproved(boolean isApproved) {
        this.isApproved = isApproved;
    }
    public Integer getApproverId() {
        return this.approverId;
    }
    
    public void setApproverId(Integer approverId) {
        this.approverId = approverId;
    }
    public boolean isIsRejected() {
        return this.isRejected;
    }
    
    public void setIsRejected(boolean isRejected) {
        this.isRejected = isRejected;
    }
    public Integer getRejectorId() {
        return this.rejectorId;
    }
    
    public void setRejectorId(Integer rejectorId) {
        this.rejectorId = rejectorId;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


