package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA



/**
 * Prstatus generated by hbm2java
 */
public class Prstatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private String description;
     private int order;
     private int usertype;

    public Prstatus() {
    }

	
    public Prstatus(String status, int order, int usertype) {
        this.status = status;
        this.order = order;
        this.usertype = usertype;
    }
    public Prstatus(String status, String description, int order, int usertype) {
       this.status = status;
       this.description = description;
       this.order = order;
       this.usertype = usertype;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }
    public int getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(int usertype) {
        this.usertype = usertype;
    }




}


