package com.tss.ocean.pojo;
// Generated 4 Aug, 2014 6:30:10 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Purrequisition generated by hbm2java
 */
public class Purrequisition  implements java.io.Serializable {


     private Integer id;
     @NotEmpty
     private String prno;
     @NotNull
     private Integer suplierid;
     @NotNull
     private Integer status;
     private Integer approvedby;
     @DateTimeFormat(pattern = "dd/MM/yyyy")
     @NotNull
     private Date createdat;
     @DateTimeFormat(pattern = "dd/MM/yyyy")
     private Date updatedat;
     @NotNull
     private Boolean isbilled;
     private BigDecimal price;
     private Integer createdby;
     private Integer updatedby;

    public Purrequisition() {
    }

	
    public Purrequisition(Date createdat) {
        this.createdat = createdat;
    }
    public Purrequisition(String prno, Integer suplierid, Integer status, Integer approvedby, Date createdat, Date updatedat, Boolean isbilled, BigDecimal price, Integer createdby, Integer updatedby) {
       this.prno = prno;
       this.suplierid = suplierid;
       this.status = status;
       this.approvedby = approvedby;
       this.createdat = createdat;
       this.updatedat = updatedat;
       this.isbilled = isbilled;
       this.price = price;
       this.createdby = createdby;
       this.updatedby = updatedby;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPrno() {
        return this.prno;
    }
    
    public void setPrno(String prno) {
        this.prno = prno;
    }
    public Integer getSuplierid() {
        return this.suplierid;
    }
    
    public void setSuplierid(Integer suplierid) {
        this.suplierid = suplierid;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getApprovedby() {
        return this.approvedby;
    }
    
    public void setApprovedby(Integer approvedby) {
        this.approvedby = approvedby;
    }
    public Date getCreatedat() {
        return this.createdat;
    }
    
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }
    public Date getUpdatedat() {
        return this.updatedat;
    }
    
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
    public Boolean getIsbilled() {
        return this.isbilled;
    }
    
    public void setIsbilled(Boolean isbilled) {
        this.isbilled = isbilled;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public Integer getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }
    public Integer getUpdatedby() {
        return this.updatedby;
    }
    
    public void setUpdatedby(Integer updatedby) {
        this.updatedby = updatedby;
    }
    
}